
image: node

stages:
  - install
 
  - build

install_dependencies:
  stage: install
  script:
    - npm install 
  artifacts:
    paths:
      - node_modules/



build_project:
  stage: build
  script:
    - npm run build 
  artifacts:
    paths:
      - ./build
